### ISSUE TITLE
Uso obrigatório de Milestones para a iteração 2

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/Insurance-Car#16]
Boa tarde a todos, em nossa última reunião de monitoria que ocorreu durante a iteração 1 (apenas os monitores) acertamos vários pontos para fidelizar um padrão de correção que seja justo para todas as equipes. Ainda na reunião definimos que a partir desta iteração (iteração 2) o uso de milestones será obrigatório. Isso para que problemas de organização e na eficiência da correção sejam sanados. Como isso funciona?

Bem, como as labels. Isso mesmo, as milestones serão as iterações que correm. Então vocês deverão criar as milestone:

Iteração 2
Iteração 3
Iteração 4

Cada milestone representará uma iteração. Dessa forma toda feature e ou artefato que for entregue deve ser marcada com a milestone que o representa. Assim como é feito com as labels.

Links que podem ajudar: 
https://guides.github.com/features/issues/
https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/

**Comment by wmof** [comment]
Feito
