### ISSUE TITLE
Relatório Iteração 2

### ISSUE THREAD

**Issue by wmof** [IF977/Insurance-Car#17]
O relatório informal de cada membro da equipe será comentado abaixo.

**Comment by wmof** [comment]
TDD de Pagamento (HU4)
Telas de Pagamento e Revisão (revisão detalhe) (HU3 e 4)
Postmortem 2

**Comment by diegodeholanda** [comment]
BDD (HU 3 e 4) sem sucesso, encontrando muita dificuldade para criação do mesmo.

**Comment by rbm4** [comment]
TDD de Revisão
Melhoramento dos testes Rspec para validação nas HU's da iteração 1
Início de reformulaçao dos controladores, visando implementação do BDD
Iniciação BDD (gemfile) e implementação da feature de  cadastro (iteração 1), ainda não finalizado pois precisa configurar as rotas e os controladores
