### ISSUE TITLE
Ajustes do Readme

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/Insurance-Car#2]
Segue minhas observações :
https://docs.google.com/a/cin.ufpe.br/document/d/1kG6BAq2QmzZtgdmzXzY6FBHeB6RDFZpnxIfRuGrANO4/edit?usp=sharing

**Comment by jorgehclinhares** [comment]
@wmof a issue continua aberta

**Comment by rbm4** [comment]
Fiz umas modificações indicadas no drive, acho que agora tá melhor

**Comment by jorgehclinhares** [comment]
ok @rbm4
