### ISSUE TITLE
Cadastro das Labels

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/Insurance-Car#3]
- Bug (label vermelha)
  Representa uma inconsistência
- Feature (label laranja) 
  Representa uma nova funcionalidade
- Docs (label azul)
  Representa entrega de alguma documentação que não seja via código
- Review (label roxa)
  Label usada para indicar uma revisão por parte dos monitores a uma determinada entrega
- Accepted (label verde)
  Label usada para indicar que a entrega foi aceita
- Rejected (label amarela)
  Label usada para indicar que a entrega não foi aceita
- Improvement (label cinza)
  Label usada para indicar que um atividade de 
  melhoria

OBS!
- As labels Accepted e Rejected só podem ser usadas pelos monitores

**Comment by wmof** [comment]
Feito
