### ISSUE TITLE
Commit que alterou as datas

### ISSUE THREAD

**Issue by wmof** [IF977/Insurance-Car#5]
![git push](https://cloud.githubusercontent.com/assets/18127570/14897505/99fcb58e-0d58-11e6-8010-b6a9749f808e.png)

Segue me anexo o commit que alterou a data referente a quando os arquivos foram entregues. 
O monitor @jorgehclinhares estava presente na hora do commit.
Embora as atividades ja tenha sido avaliadas, vale a observação que está não é a data que foram enviadas. @vinicius3w

**Comment by jorgehclinhares** [comment]
Ok!
