### ISSUE TITLE
TDD BDD HU 1 e 2

### ISSUE THREAD

**Issue by wmof** [IF977/Insurance-Car#8]
Implementar teste TDD BDD para as Historias do usuário 1 e 2

Responsáveis:
Edson @ensn96 
Diego @diegodeholanda 
Ricardo @rbm4

**Comment by wmof** [comment]
TDD OK

**Comment by ensn96** [comment]
Assim como Diego estudei a implementação do BDD porém não obtive êxito em colocar essa implementação em prática...

**Comment by jorgehclinhares** [comment]
Revisado, testes TDD OK - testes BDD não implementados.
